export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Bank",
  headline: "Unlimited Transaction with zero fees",
  description: "Get access to our exclusive app that allows you to send unlimited transactions without getting charrged any fees.",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require('../../images/svg-1.svg'),
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
}

export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Premium Bank",
  headline: "Unlimited Transaction with zero fees",
  description: "Get access to our exclusive app that allows you to send unlimited transactions without getting charrged any fees.",
  buttonLabel: "Get Started",
  imgStart: true,
  img: require('../../images/svg-2.svg'),
  alt: "car",
  dark: false,
  primary: false,
  darkText: true,
}

export const homeObjThree = {
  id: "signup",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Bank",
  headline: "Unlimited Transaction with zero fees",
  description: "Get access to our exclusive app that allows you to send unlimited transactions without getting charrged any fees.",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require('../../images/svg-3.svg'),
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
}